# Generated by Django 6.1 on 2026-08-11 05:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='True if this case needs analyst review or sandbox escalation'),
        ),
        migrations.AddField(
            model_name='submission',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Aggregate score from static analysis (YARA severity sum)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='static_report',
            field=models.JSONField(blank=True, default=dict, help_text='Full structured output from the static analysis scanner'),
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('PENDING', 'Pending analysis'), ('CLEAN', 'Clean'), ('SUSPICIOUS', 'Suspicious'), ('MALICIOUS', 'Malicious')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\lenovo\\Web_DEV\\AD\\Website\\Backend\\quarantine'), upload_to='submissions/%Y/%m/'),
        ),
    ]
